version: '3.7'

services:
  mermaid:
    build:
      context: .
      target: mermaid-dev

    environment:
      - SERVICE_FQDN_MERMAID_3000
      - SERVICE_FQDN_MERMAID_24678

    ports:
      - "3000:3000"
      - "24678:24678"

    # Short syntax for a bind mount
    volumes:
      - "./src:/app/src"
